apiVersion: v1
kind: Service
metadata:
  name: back-pec-2-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: back-pec-2
    component: backend
    resource: app
spec:
  type: ClusterIP
  selector:
    app: back-pec-2
    component: backend
    resource: app
  ports:
    - name: http
      port: 8080
      targetPort: 8080