apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-pec-2-deployment
  labels:
    app: kube-pec-2
    component: front-end
    resource: flutter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-pec-2
      component: front-end
      resource: flutter
  template:
    metadata:
      labels:
        app: kube-pec-2
        component: front-end
        resource: flutter
    spec:
      containers:
        - name: front-end
          image: charlineroyer937/frontend-pec-2:1.1.7
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: front-pec-2-configmap-env-prod
                  key: API_BASE_URL
            - name: API_BASE_URL_WEB
              valueFrom:
                configMapKeyRef:
                  name: front-pec-2-configmap-env-prod
                  key: API_BASE_URL_WEB
            - name: NGINX_PORT
              valueFrom:
                configMapKeyRef:
                  name: front-pec-2-configmap-env-prod
                  key: NGINX_PORT
            - name: PORTDOCKER
              valueFrom:
                configMapKeyRef:
                  name: front-pec-2-configmap-env-prod
                  key: PORTDOCKER
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: front-pec-2-configmap-env-prod
                  key: BACKEND_URL
          ports:
            - containerPort: 80
