apiVersion: v1
kind: Service
metadata:
  name: front-pec-2-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: kube-pec-2
    component: front-end
    resource: flutter
spec:
  selector:
    app: kube-pec-2
    component: front-end
    resource: flutter
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP